env: ma_mujoco

env_args:
  map_name: "swimmer"
  episode_length: 1000
  scenario_name: 'swimmer'
  num_agents: 2
  num_angle_tasks: 5
  max_task_angles: 30
    
  

test_nepisode: 10
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 5000000
