env: smac_climbreward

env_args:
  original_battle_reward_factor: 0.01
  new_suboptimal_reward_scale: 0.5
  new_getdamage_penalty_scale: 0
  new_risk_penalty_scale: 1
  new_defeat_bonus: 0
  target_enemy: 0
  K_agents: 3 
  continuing_episode: False
  difficulty: "7"
  game_version: null
  map_name: "3m"
  move_amount: 2
  obs_all_health: True
  obs_instead_of_state: False
  obs_last_action: False
  obs_own_health: True
  obs_pathing_grid: False
  obs_terrain_height: False
  obs_timestep_number: False
  reward_death_value: 10
  reward_defeat: 0
  reward_negative_scale: 0.5
  reward_only_positive: True
  reward_scale: True
  reward_scale_rate: 20
  reward_sparse: False
  reward_win: 200
  replay_dir: ""
  replay_prefix: ""
  state_last_action: True
  state_timestep_number: False
  step_mul: 8
  seed: null
  heuristic_ai: False
  heuristic_rest: False
  debug: False

test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 2100000
save_model: True
use_tensorboard: True
save_buffer: False
save_model_interval: 200000
